# Generated by Django 4.1.3 on 2022-11-29 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_students_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='image',
        ),
    ]
